/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajocolaborativogit;

/**
 *
 * @author josep
 */
public class FrmPresentacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmPresentación
     */
    public FrmPresentacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JButton();
        btnSiguiente2 = new javax.swing.JButton();
        btnPresentadora = new javax.swing.JButton();
        lblFondoPresentacion = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTexto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/texto1.png"))); // NOI18N
        getContentPane().add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 260));

        lblTexto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/texto2.png"))); // NOI18N
        getContentPane().add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 260, 260));

        btnSiguiente1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSiguiente1.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha48.png"))); // NOI18N
        btnSiguiente1.setText("SIGUIENTES");
        btnSiguiente1.setToolTipText("");
        btnSiguiente1.setContentAreaFilled(false);
        btnSiguiente1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguiente1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha48.png"))); // NOI18N
        btnSiguiente1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha64.png"))); // NOI18N
        btnSiguiente1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSiguiente1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 170, 110));

        btnSiguiente2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSiguiente2.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha48.png"))); // NOI18N
        btnSiguiente2.setText("SIGUIENTES");
        btnSiguiente2.setToolTipText("");
        btnSiguiente2.setContentAreaFilled(false);
        btnSiguiente2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguiente2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha48.png"))); // NOI18N
        btnSiguiente2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha64.png"))); // NOI18N
        btnSiguiente2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSiguiente2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 170, 110));

        btnPresentadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Presentadora.png"))); // NOI18N
        btnPresentadora.setContentAreaFilled(false);
        getContentPane().add(btnPresentadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 100, 470, 550));

        lblFondoPresentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoPresentacion.jpg"))); // NOI18N
        getContentPane().add(lblFondoPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 850, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
        lblTexto1.setVisible(false);
        btnSiguiente1.setVisible(false);
        
    }//GEN-LAST:event_btnSiguiente1ActionPerformed

    private void btnSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente2ActionPerformed
        FrmHuevo huevo = new FrmHuevo();
        huevo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguiente2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPresentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPresentadora;
    private javax.swing.JButton btnSiguiente1;
    private javax.swing.JButton btnSiguiente2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblFondoPresentacion;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    // End of variables declaration//GEN-END:variables
}
